# Generated by Django 6.0.5 on 2026-06-12 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='The classification type of the document (e.g., INVOICE, RECEIPT, PASSPORT).', max_length=50)),
                ('file', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected / Invalid')], default='PENDING', help_text='The current processing status of the file.', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp when this file hit the server.')),
                ('extracted_text', models.TextField(blank=True, help_text='The raw text extracted via your Python OCR parser.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
