# Generated by Django 6.0.5 on 2026-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Awaiting Scan'), ('PROCESSED', 'OCR Processed'), ('FAILED', 'OCR Failed'), ('SKIPPED', 'OCR Skipped')], default='PENDING', help_text='Tracks whether text extraction via Python OCR engine succeeded or threw errors.', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The current processing status of the file.', max_length=20),
        ),
    ]
