# Generated by Django 6.0.5 on 2026-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_filename_document_ocr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('PROCESSED', 'OCR Processed'), ('FAILED', 'OCR Failed')], default='PENDING', help_text='Tracks whether text extraction via Python OCR engine succeeded or threw errors.', max_length=20),
        ),
    ]
