# Generated by Django 6.0.5 on 2026-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_remarks_alter_document_ocr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_accuracy',
            field=models.FloatField(default=0.0, help_text='The calculated mean confidence level percentage of the parsed text.'),
        ),
    ]
