# Generated by Django 6.0.5 on 2026-06-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved by DocVerify'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The current processing status of the file.', max_length=20),
        ),
    ]
