# Generated by Django 6.0.5 on 2026-07-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan_type',
            field=models.CharField(choices=[('PAY AS YOU VERIFY', 'Pay As You Verify (₹49)'), ('STARTER PACK', 'Starter Pack (₹99)'), ('MONTHLY PREMIUM', 'Monthly Premium Pass (₹299)')], max_length=50),
        ),
    ]
