# Generated by Django 6.0.5 on 2026-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_payment_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan_type',
            field=models.CharField(choices=[('PAY_AS_YOU_VERIFY', 'Pay-As-You-Verify (₹49)'), ('STARTER_PACK', 'Starter Pack (₹99)'), ('MONTHLY_PREMIUM', 'Monthly Premium Pass (₹299)')], max_length=50),
        ),
    ]
