# Generated by Django 6.0.5 on 2026-07-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_payment_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
