# Generated by Django 6.0.5 on 2026-08-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
