# Generated by Django 6.0.5 on 2026-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_payment_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auto_verified',
            field=models.BooleanField(default=False, help_text='True if the current status was set by the automatic verification engine, False if set/overridden by an admin.'),
        ),
    ]
