# Generated by Django 6.0.5 on 2026-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_auto_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='estimated_seconds',
            field=models.IntegerField(default=5, help_text='Estimated seconds remaining for background OCR processing.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'OCR Processed'), ('FAILED', 'OCR Failed')], default='PENDING', help_text='Tracks whether text extraction via Python OCR engine succeeded or threw errors.', max_length=20),
        ),
    ]
