# Generated by Django 6.0.5 on 2026-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
